CREATE DATABASE VETERINARIA;

USE VETERINARIA;

CREATE TABLE TIPOS_ANIMAIS(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ESPECIE VARCHAR(50)
);

CREATE TABLE ANIMAIS(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ESPECIE VARCHAR(50),
	NOME VARCHAR(100),
    DT_NASC DATE NOT NULL,
    COR VARCHAR(15),
    PESO INT NOT NULL,
    ALTURA INT NOT NULL,
    ID_TIPOS_ANIMAIS INT NOT NULL,
    CONSTRAINT FK_ID_TIPOS_ANIMAIS
		FOREIGN KEY (ID_TIPOS_ANIMAIS)
        REFERENCES TIPOS_ANIMAIS(ID)
);

CREATE TABLE VACINACAO(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID_ANIMAL INT NOT NULL,
	NOME_VACINA VARCHAR(100),
	DT_APLIC DATE,
    CONSTRAINT FK_ID_ANIMAL
		FOREIGN KEY (ID_ANIMAL)
        REFERENCES ANIMAIS(ID)
);

SELECT * FROM `TIPOS_ANIMAIS`;
SELECT ID, ESPECIE FROM TIPOS_ANIMAIS;

SELECT * FROM `ANIMAIS`;
SELECT ID, ESPECIE, NOME, DT_NASC, COR, PESO, ALTURA FROM ANIMAIS;

SELECT * FROM `VACINACAO`;
SELECT ID, ID_ANIMAL, NOME_VACINA, DT_APLIC FROM VACINACAO;

