CREATE DATABASE TRANSPORTE_AEREO;
USE TRANSPORTE_AEREO;

CREATE TABLE AERONAVE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TIPO VARCHAR(100) NOT NULL,
    NUMERO_POLTRONAS INT NOT NULL
);

CREATE TABLE AEROPORTO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    CIDADE VARCHAR(100),
    ESTADO VARCHAR(100),
    PAIS VARCHAR(100)
);

CREATE TABLE VOO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_AERONAVE INT NOT NULL,
    ID_ORIGEM INT NOT NULL,
    ID_DESTINO INT NOT NULL,
    HORARIO_SAIDA DATETIME NOT NULL,
    HORARIO_CHEGADA DATETIME NOT NULL,
    FOREIGN KEY (ID_AERONAVE) REFERENCES AERONAVE(ID),
    FOREIGN KEY (ID_ORIGEM) REFERENCES AEROPORTO(ID),
    FOREIGN KEY (ID_DESTINO) REFERENCES AEROPORTO(ID)
);

CREATE TABLE ESCALA (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_VOO INT NOT NULL,
    ID_SAIDA INT NOT NULL,
    HORARIO_SAIDA DATETIME NOT NULL,
    FOREIGN KEY (ID_SAIDA) REFERENCES VOO(ID),
    FOREIGN KEY (ID_SAIDA) REFERENCES AEROPORTO(ID)
);

CREATE TABLE POLTRONA (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_AERONAVE INT NOT NULL,
    NUMERO_POLTRONA VARCHAR(5),
    LOCALIZACAO ENUM('JANELA', 'CORREDOR', 'MEIO'),
    LADO ENUM('ESQUERDA', 'DIREITA'),
    FOREIGN KEY (ID_AERONAVE) REFERENCES AERONAVE(ID)
);

CREATE TABLE POLTRONA_DISPONIVEL (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_VOO INT NOT NULL,
    ID_POLTRONA INT NOT NULL,
    DISPONIVEL BOOLEAN DEFAULT TRUE,
    FOREIGN KEY (ID_VOO) REFERENCES VOO(ID),
    FOREIGN KEY (ID_POLTRONA) REFERENCES POLTRONA(ID)
);

CREATE TABLE CLIENTE (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_VOO INT NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    CPF VARCHAR(11) NOT NULL,
    IDADE VARCHAR(3) NOT NULL,
    SEXO ENUM('MASCULINO', 'FEMININO'),
    FOREIGN KEY (ID_VOO) REFERENCES VOO(ID)
);

CREATE TABLE CLIENTE_PREFERENCIAL (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_CLIENTE_PREFERENCIAL INT NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100),
    TELEFONE VARCHAR(20),
    ENDERECO TEXT,
    FOREIGN KEY (ID_CLIENTE_PREFERENCIAL) REFERENCES CLIENTE(ID)
);




